apiExternalUrl: "http://{API Service Public IP Address with port if not 80, ex. 4.194.69.254}"
evaluationServerExternalUrl: "http://{Evaluation Service Public IP Address with port if not 80, ex. 4.193.158.12}"

ui:
  service:
    type: LoadBalancer
    port: 80
    staticIP: {UI Portal Public IP Address, ex. 4.194.13.155}


api:
  service:
    type: LoadBalancer
    port: 80
    staticIP: {API Service Public IP Address, ex. 4.194.69.254}

els:
  service:
    type: LoadBalancer
    port: 80
    staticIP: {Evaluation Service Public IP Address, ex. 4.193.158.12}