{{- if .Values.els.ingress.enabled -}}
{{- $fullName := (include "featbit.fullname" .) -}}
{{- $svcName := (include "els.svc.name" .) -}}
{{- $svcPort := 80 -}}
{{- if and .Values.global.ingressClassName (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.els.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.els.ingress.annotations "kubernetes.io/ingress.class" .Values.global.ingressClassName }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $fullName }}-els-ingress
  labels:
    {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
    {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
    {{- with .Values.els.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.global.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.ingressClassName }}
  {{- end }}
  {{- if and .Values.els.ingress.tls.enabled .Values.els.ingress.tls.secretName .Values.els.ingress.host }}
  tls:
    - secretName: {{ .Values.els.ingress.tls.secretName }}
      hosts:
        - {{ .Values.els.ingress.host }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ default "/" .Values.els.ingress.path }}
            {{- if and .Values.els.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ default "ImplementationSpecific" .Values.els.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $svcName }}
              servicePort: {{ $svcPort }}
              {{- end }}
      {{- if .Values.els.ingress.host }}
      host: {{ .Values.els.ingress.host }}
      {{- end }}
{{- end }}
