apiExternalUrl: "http://4.193.158.12"
evaluationServerExternalUrl: "http://4.193.159.40"
autoDiscovery: true

ui:
  service:
    type: LoadBalancer
    port: 80
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_bestpractice_featbit-k8s-trial_southeastasia
    staticIP: 4.194.69.254

api:
  service:
    type: LoadBalancer
    port: 80
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_bestpractice_featbit-k8s-trial_southeastasia
    staticIP: 4.193.158.12

els:
  service:
    type: LoadBalancer
    port: 80
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_bestpractice_featbit-k8s-trial_southeastasia
    staticIP: 4.193.159.40