apiExternalUrl: ""
evaluationServerExternalUrl: ""
autoDiscovery: true

isPro: true

ui:
  service:
    type: LoadBalancer
    port: 80


api:
  service:
    type: LoadBalancer
    port: 80

els:
  service:
    type: LoadBalancer
    port: 80


kafka:
  enabled: true

clickhouse:
  enabled: true